Version: "1.7.0-dev"


Excluded:
  - spec/**/*.cr
  - lib/**/*
  - temp/**/*
  - vendor
  - crystal
  - src/**/*.bak

Metrics/CyclomaticComplexity:
  Excluded:
    - src/bubbles/cursor.cr
    - src/bubbles/list.cr
    - src/bubbles/list/defaultitem.cr
    - src/bubbles/textinput.cr
